In [1]:
import numpy as np

In [3]:
n_array_1=np.random.randint(1,30,8)

In [4]:
n_array_1

array([27, 24, 26, 18, 20, 18, 22, 26])

In [5]:
n_array_1[3]

18

In [6]:
n_array_1[2:7]

array([26, 18, 20, 18, 22])

In [7]:
n_array_1[:3]

array([27, 24, 26])

In [8]:
n_array_2=np.arange(1,7)

In [9]:
n_array_2

array([1, 2, 3, 4, 5, 6])

In [10]:
n_array_2[:3]=7

In [11]:
n_array_2

array([7, 7, 7, 4, 5, 6])

In [12]:
n_array_3=np.random.randint(1,100,20)

In [13]:
n_array_3

array([68, 94, 55, 28,  9, 35, 63, 65,  9, 44, 68, 10, 43,  2, 50, 90,  9,
       52, 78,  6])

In [14]:
n_array_3=n_array_3.reshape(5,4)

In [15]:
n_array_3

array([[68, 94, 55, 28],
       [ 9, 35, 63, 65],
       [ 9, 44, 68, 10],
       [43,  2, 50, 90],
       [ 9, 52, 78,  6]])

In [16]:
n_array_3[4]

array([ 9, 52, 78,  6])

In [17]:
n_array_3[3,0]

43

In [18]:
n_array_3[:2]

array([[68, 94, 55, 28],
       [ 9, 35, 63, 65]])

In [20]:
n_array_3[:,2:4]

array([[55, 28],
       [63, 65],
       [68, 10],
       [50, 90],
       [78,  6]])

In [21]:
n_array_3[:,(2,3)]

array([[55, 28],
       [63, 65],
       [68, 10],
       [50, 90],
       [78,  6]])

In [22]:
n_array_4=np.arange(1,7)

In [23]:
n_array_4

array([1, 2, 3, 4, 5, 6])

In [24]:
n_array_4_SC=n_array_4.view()

In [25]:
n_array_4_SC

array([1, 2, 3, 4, 5, 6])

In [26]:
n_array_4[3]*=7

In [27]:
n_array_4

array([ 1,  2,  3, 28,  5,  6])

In [28]:
n_array_4_SC

array([ 1,  2,  3, 28,  5,  6])

In [29]:
n_array_4_SC[2]+=5

In [30]:
n_array_4_SC

array([ 1,  2,  8, 28,  5,  6])

In [31]:
n_array_4

array([ 1,  2,  8, 28,  5,  6])

In [32]:
n_array_4_DC=n_array_4.copy()

In [33]:
n_array_4_DC

array([ 1,  2,  8, 28,  5,  6])

In [34]:
n_array_4_DC[1]=-5

In [35]:
n_array_4_DC

array([ 1, -5,  8, 28,  5,  6])

In [36]:
n_array_4

array([ 1,  2,  8, 28,  5,  6])

In [37]:
n_array_4_SC

array([ 1,  2,  8, 28,  5,  6])