In [3]:
import numpy as np

In [4]:
integers=np.array([[1,2,3 ,4],[5,6,7 ,13]])

In [3]:
integers

array([[ 1,  2,  3,  4],
       [ 5,  6,  7, 13]])

In [4]:
floats=np.array([0.0, 0.10,0.12,0.13,0.5 ,0.63])

In [5]:
floats

array([0.  , 0.1 , 0.12, 0.13, 0.5 , 0.63])

In [6]:
integers.ndim##

2

In [7]:
floats.ndim

1

In [8]:
integers.shape

(2, 4)

In [10]:
floats.shape

(6,)

In [11]:
integers.size

8

In [12]:
floats.size

6

In [13]:
for row in integers:
    print(row)

[1 2 3 4]
[ 5  6  7 13]


In [7]:
for i in integers.flat:
    print(i, end=" ")

1 2 3 4 5 6 7 13 

In [16]:
for i in integers.flat:
    print(i)

1
2
3
4
5
6
7
13


In [17]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.ones((3,4),dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.full((3,5),13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(3,8)

array([3, 4, 5, 6, 7])

In [24]:
np.arange(20,1,-3)

array([20, 17, 14, 11,  8,  5,  2])

In [9]:
np.linspace(0,50)

array([ 0.        ,  1.02040816,  2.04081633,  3.06122449,  4.08163265,
        5.10204082,  6.12244898,  7.14285714,  8.16326531,  9.18367347,
       10.20408163, 11.2244898 , 12.24489796, 13.26530612, 14.28571429,
       15.30612245, 16.32653061, 17.34693878, 18.36734694, 19.3877551 ,
       20.40816327, 21.42857143, 22.44897959, 23.46938776, 24.48979592,
       25.51020408, 26.53061224, 27.55102041, 28.57142857, 29.59183673,
       30.6122449 , 31.63265306, 32.65306122, 33.67346939, 34.69387755,
       35.71428571, 36.73469388, 37.75510204, 38.7755102 , 39.79591837,
       40.81632653, 41.83673469, 42.85714286, 43.87755102, 44.89795918,
       45.91836735, 46.93877551, 47.95918367, 48.97959184, 50.        ])

In [27]:
np.linspace(0,50,num=5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [28]:
np.arange(1,31).reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [29]:
np.arange(1,31).reshape(4,6)

ValueError: cannot reshape array of size 30 into shape (4,6)

In [10]:
np.random.randint(1,20,6)

array([11, 14, 13, 16, 11,  7])

In [34]:
Rand_Array = np.random.randint(1,100,15)

In [35]:
Rand_Array.sum()

618

In [36]:
Rand_Array.max()

90

In [37]:
Rand_Array.min()

4

In [39]:
Rand_Array.mean()

41.2

In [40]:
Rand_Array.std()

25.69357896440276