In [1]:
import numpy as np

In [2]:
vector_1=np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
vector_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
vector_1*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
vector_1+5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
vector_2=np.array([2,1,3,4,5,7,8,6,10,9])
vector_2

array([ 2,  1,  3,  4,  5,  7,  8,  6, 10,  9])

In [7]:
vector_1+vector_2

array([ 3,  3,  6,  8, 10, 13, 15, 14, 19, 19])

In [5]:
matrix_1=np.random.randint(1,100,25).reshape(5,5)

In [6]:
matrix_1

array([[89, 40, 89, 12, 81],
       [91, 70, 60, 48, 49],
       [17, 98, 15, 47, 60],
       [51, 25, 33, 22, 88],
       [20, 52, 44, 40, 38]])

In [7]:
matrix_1+5

array([[ 94,  45,  94,  17,  86],
       [ 96,  75,  65,  53,  54],
       [ 22, 103,  20,  52,  65],
       [ 56,  30,  38,  27,  93],
       [ 25,  57,  49,  45,  43]])

In [8]:
matrix_1*3

array([[267, 120, 267,  36, 243],
       [273, 210, 180, 144, 147],
       [ 51, 294,  45, 141, 180],
       [153,  75,  99,  66, 264],
       [ 60, 156, 132, 120, 114]])

In [9]:
tensor_1=np.random.randint(1,100,45).reshape(3,3,5)
tensor_1

array([[[61, 65, 22, 44, 80],
        [59, 93, 48, 29, 50],
        [62, 74, 23, 85, 15]],

       [[26,  2, 99, 50, 13],
        [69, 85, 91, 68,  9],
        [95, 68, 10, 83,  1]],

       [[30, 16, 49, 25, 54],
        [52, 44, 74, 19,  5],
        [98, 94, 10, 72, 32]]])

In [13]:
print(vector_1.shape)

(10,)


In [14]:
print(matrix_1.shape)

(5, 5)


In [16]:
print(tensor_1.shape)

(3, 3, 5)


In [17]:
print(vector_1.size)

10


In [18]:
print(matrix_1.size)

25


In [19]:
print(tensor_1.size)

45


In [20]:
vector_1.dot(vector_2)

380

In [21]:
matrix_a=np.random.randint(10,size=(2,2))
matrix_a

array([[5, 4],
       [5, 1]])

In [22]:
matrix_b=np.matrix(np.random.randint(10,size=(2,2)))

In [23]:
matrix_b

matrix([[3, 9],
        [5, 4]])

In [24]:
matrix_a[0,0]

5

In [25]:
matrix_a[0]

array([5, 4])

In [27]:
matrix_a[:,0]

array([5, 5])

In [28]:
matrix_c=matrix_a.dot(matrix_b)
matrix_c

matrix([[35, 61],
        [20, 49]])

In [29]:
matrix_a

array([[5, 4],
       [5, 1]])

In [30]:
matrix_b

matrix([[3, 9],
        [5, 4]])

In [17]:
np.identity(4).astype(int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [33]:
matrix_d=np.random.randint(10,size=(4,4))
matrix_d

array([[5, 9, 5, 4],
       [0, 2, 1, 5],
       [0, 9, 8, 6],
       [8, 5, 4, 3]])

In [35]:
np.dot(matrix_d,np.identity(4))

array([[5., 9., 5., 4.],
       [0., 2., 1., 5.],
       [0., 9., 8., 6.],
       [8., 5., 4., 3.]])

In [36]:
matrix_e=np.linalg.inv(matrix_d)    ##INVERSE
matrix_e

array([[-0.02075702,  0.001221  , -0.05616606,  0.13797314],
       [ 0.33211233, -0.01953602, -0.1013431 , -0.20757021],
       [-0.32234432, -0.15750916,  0.24542125,  0.2014652 ],
       [-0.06837607,  0.23931624, -0.00854701,  0.04273504]])

In [37]:
np.dot(matrix_d,matrix_e)

array([[ 1.00000000e+00,  1.11022302e-16,  1.11022302e-16,
         2.22044605e-16],
       [ 5.55111512e-17,  1.00000000e+00, -2.77555756e-17,
        -5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.11022302e-16,
         1.00000000e+00]])

In [38]:
matrix_f=np.random.randint(10,size=(3,4))
matrix_f

array([[4, 5, 9, 0],
       [0, 3, 7, 2],
       [8, 6, 2, 8]])

In [39]:
matrix_g=np.random.randint(10,size=(4,3))
matrix_g

array([[9, 0, 7],
       [5, 9, 8],
       [4, 0, 5],
       [7, 3, 8]])

In [40]:
np.dot(matrix_f,matrix_g)

array([[ 97,  45, 113],
       [ 57,  33,  75],
       [166,  78, 178]])

In [41]:
np.dot(matrix_g,matrix_f)

array([[ 92,  87,  95,  56],
       [ 84, 100, 124,  82],
       [ 56,  50,  46,  40],
       [ 92,  92, 100,  70]])

In [42]:
vector_3=np.random.randint(1,15,4)
vector_3

array([10, 14,  1, 11])

In [44]:
np.vdot(vector_3,matrix_a)

122

In [45]:
matrix_a

array([[5, 4],
       [5, 1]])

In [46]:
matrix_b

matrix([[3, 9],
        [5, 4]])

In [47]:
np.matmul(matrix_a,matrix_b)

matrix([[35, 61],
        [20, 49]])

In [48]:
matrix_det=np.matrix(np.random.randint(10,size=(2,2)))
matrix_det

matrix([[3, 7],
        [5, 1]])

In [49]:
np.linalg.det(matrix_det)   ##Determinant

-32.0

In [11]:
m1 = np.random.randint(1,10,6).reshape(2,3)
m2 = np.random.randint(1,20,6).reshape(3,2)

In [13]:
m1


array([[3, 9, 7],
       [4, 2, 9]])

In [14]:
m2

array([[ 9, 16],
       [19, 10],
       [ 8, 17]])

In [15]:
m1.dot(m2)

array([[254, 257],
       [146, 237]])

In [16]:
np.dot(m1,m2)

array([[254, 257],
       [146, 237]])

In [18]:
np.matmul(m1,m2)

array([[254, 257],
       [146, 237]])

In [22]:
m3 = np.arange(1,5,1).reshape(2,2)
m3

array([[1, 2],
       [3, 4]])

In [23]:
inverse = np.linalg.inv(m3)

In [24]:
inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [25]:
determinant = np.linalg.det(m3)

In [27]:
determinant.astype(int)

-2