In [1]:
import numpy as np

In [4]:
numbers_1=np.arange(1,10,2)
numbers_rand=np.random.randint(1,20,5)

In [5]:
numbers_1

array([1, 3, 5, 7, 9])

In [6]:
numbers_rand

array([19,  8,  1, 19, 15])

In [7]:
numbers_1+numbers_rand

array([20, 11,  6, 26, 24])

In [10]:
numbers_1*numbers_rand

array([361,  64,   1, 361, 225])

In [11]:
numbers_1/3

array([6.33333333, 2.66666667, 0.33333333, 6.33333333, 5.        ])

In [12]:
numbers_rand/3

array([6.33333333, 2.66666667, 0.33333333, 6.33333333, 5.        ])

In [13]:
numbers_1+=5

In [14]:
numbers_rand+=3

In [15]:
numbers_1

array([27, 16,  9, 27, 23])

In [16]:
numbers_rand

array([27, 16,  9, 27, 23])

In [18]:
np.sqrt(numbers_1)

array([5.19615242, 4.        , 3.        , 5.19615242, 4.79583152])

In [19]:
np.sqrt(numbers_rand)

array([5.19615242, 4.        , 3.        , 5.19615242, 4.79583152])

In [20]:
s_1=np.arange(1,10,2)
s_2=np.arange(1,11,3)

In [21]:
s_1

array([1, 3, 5, 7, 9])

In [22]:
s_2

array([ 1,  4,  7, 10])

In [23]:
s_1+s_2

ValueError: operands could not be broadcast together with shapes (5,) (4,) 