In [2]:
import numpy as np

In [6]:
array_r_1=np.random.randint(1,150,20)

In [5]:
array_r_1

array([105,  79,  54, 124,  56,  30, 138, 118, 139,  86,  90, 134,  24,
        98, 103,  75,  24, 129,  60,  45])

In [6]:
array_r_1.sum()

1711

In [7]:
array_r_1.max()

139

In [8]:
array_r_1.min()

24

In [9]:
array_r_1.mean()

85.55

In [3]:
array_2=np.arange(1,60,3)

In [11]:
array_2

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58])

In [13]:
array_2+array_r_1

array([106,  83,  61, 134,  69,  46, 157, 140, 164, 114, 121, 168,  61,
       138, 146, 121,  73, 181, 115, 103])

In [14]:
array_r_1

array([105,  79,  54, 124,  56,  30, 138, 118, 139,  86,  90, 134,  24,
        98, 103,  75,  24, 129,  60,  45])

In [15]:
array_r_1[10]

90

In [16]:
r_element=array_r_1[np.random.randint(1,21,1)]

In [17]:
r_element

array([54])

In [18]:
index_value=np.where(array_r_1==r_element)

In [19]:
index_value

(array([2], dtype=int64),)

In [7]:
array_r_2=array_r_1.reshape(4,5)


In [8]:
array_r_2

array([[106,   5,  30, 128,  45],
       [129, 126,  88,  84, 140],
       [ 27,  75,  59,  29, 132],
       [ 17, 148, 109,  66, 109]])

In [10]:
array_r_2[:,(2,3)]

array([[ 30, 128],
       [ 88,  84],
       [ 59,  29]])

In [23]:
array_r_b=np.pad(array_r_2,pad_width= 1, mode = 'constant', constant_values = 0)

In [24]:
print(array_r_b)

[[  0   0   0   0   0   0   0]
 [  0 105  79  54 124  56   0]
 [  0  30 138 118 139  86   0]
 [  0  90 134  24  98 103   0]
 [  0  75  24 129  60  45   0]
 [  0   0   0   0   0   0   0]]


In [25]:
array_r_3=np.random.randint(1,100,30)

In [26]:
array_r_3=array_r_3.reshape(6,5)

In [27]:
array_r_3

array([[27, 12, 72, 24, 15],
       [14, 21, 81, 72, 92],
       [16, 87, 24, 93, 65],
       [25, 22, 46, 18, 54],
       [18, 79, 43, 89, 50],
       [87, 37, 98, 80, 80]])

In [28]:
array_r_3.sort()

In [29]:
array_r_3

array([[12, 15, 24, 27, 72],
       [14, 21, 72, 81, 92],
       [16, 24, 65, 87, 93],
       [18, 22, 25, 46, 54],
       [18, 43, 50, 79, 89],
       [37, 80, 80, 87, 98]])

In [31]:
np.put(array_r_3,np.random.choice(range(5,6),replace=False),1)

In [32]:
array_r_3

array([[12, 15, 24, 27, 72],
       [ 1, 21, 72, 81, 92],
       [16, 24, 65, 87, 93],
       [18, 22, 25, 46, 54],
       [18, 43, 50, 79, 89],
       [37, 80, 80, 87, 98]])

In [33]:
array_5=np.arange(1,101).reshape(10,10)

In [34]:
array_5

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [35]:
array_5[5:]

array([[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [36]:
array_5[4:,5:]

array([[ 46,  47,  48,  49,  50],
       [ 56,  57,  58,  59,  60],
       [ 66,  67,  68,  69,  70],
       [ 76,  77,  78,  79,  80],
       [ 86,  87,  88,  89,  90],
       [ 96,  97,  98,  99, 100]])

In [37]:
array_5[2:5,4:7]

array([[25, 26, 27],
       [35, 36, 37],
       [45, 46, 47]])

In [38]:
array_5

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [39]:
array_5[:,9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [40]:
array_a=((np.random.rand(15)*10).astype(int)).reshape(3,5)

In [41]:
array_b=((np.random.rand(15)*10).astype(int)).reshape(3,5)

In [42]:
array_a

array([[5, 1, 1, 0, 8],
       [6, 7, 2, 9, 4],
       [3, 3, 5, 9, 0]])

In [43]:
array_b

array([[3, 9, 6, 3, 3],
       [0, 5, 8, 3, 0],
       [2, 8, 9, 8, 2]])

In [44]:
array_a+array_b

array([[ 8, 10,  7,  3, 11],
       [ 6, 12, 10, 12,  4],
       [ 5, 11, 14, 17,  2]])

In [45]:
array_a*array_b

array([[15,  9,  6,  0, 24],
       [ 0, 35, 16, 27,  0],
       [ 6, 24, 45, 72,  0]])

In [46]:
array_a/array_b

<ipython-input-46-92ed3b6eb0a7>:1: RuntimeWarning: divide by zero encountered in true_divide
  array_a/array_b


array([[1.66666667, 0.11111111, 0.16666667, 0.        , 2.66666667],
       [       inf, 1.4       , 0.25      , 3.        ,        inf],
       [1.5       , 0.375     , 0.55555556, 1.125     , 0.        ]])

In [47]:
(array_a/array_b).astype(int)

<ipython-input-47-863a38075a6d>:1: RuntimeWarning: divide by zero encountered in true_divide
  (array_a/array_b).astype(int)


array([[          1,           0,           0,           0,           2],
       [-2147483648,           1,           0,           3, -2147483648],
       [          1,           0,           0,           1,           0]])