In [1]:
import numpy as np

In [3]:
array_1=np.random.randint(1,500,15).reshape(3,5)
array_1

array([[393, 427, 173, 304, 370],
       [198, 496, 482, 220, 163],
       [ 67, 139, 284, 277, 330]])

In [6]:
array_2=array_1.reshape(3,5)

In [7]:
array_2

array([[393, 427, 173, 304, 370],
       [198, 496, 482, 220, 163],
       [ 67, 139, 284, 277, 330]])

In [4]:
index_value=np.argpartition(array_1, -5)[-5:]
index_value

array([[2, 1, 0, 3, 4],
       [4, 1, 2, 3, 0],
       [0, 1, 2, 3, 4]], dtype=int64)

In [8]:
np.sort(array_1[index_value])

array([369, 392, 419, 467, 468])

In [10]:
index_value_2=np.argpartition(array_2, -5,axis=2)[-5:]

ValueError: kth(=-2) out of bounds (3)

In [9]:
index_value_2

array([[2, 1, 0, 3, 4],
       [4, 1, 2, 3, 0],
       [0, 1, 2, 3, 4]], dtype=int64)

In [14]:
np.sort(array_2[index_value_2])

array([[[ 39,  96, 158, 224, 298],
        [ 39,  96, 158, 224, 298],
        [205, 357, 366, 369, 392],
        [ 39,  96, 158, 224, 298],
        [ 39,  96, 158, 224, 298]],

       [[ 97, 242, 419, 467, 468],
        [ 97, 242, 419, 467, 468],
        [ 97, 242, 419, 467, 468],
        [ 97, 242, 419, 467, 468],
        [ 97, 242, 419, 467, 468]],

       [[205, 357, 366, 369, 392],
        [205, 357, 366, 369, 392],
        [ 39,  96, 158, 224, 298],
        [205, 357, 366, 369, 392],
        [205, 357, 366, 369, 392]]])

In [15]:
index_value_3=np.argpartition(array_2,ravel(),-5)[-5:]

NameError: name 'ravel' is not defined

In [16]:
index_value_3

NameError: name 'index_value_3' is not defined

In [17]:
index_value

array([13, 11,  6,  5,  7], dtype=int64)

In [18]:
array_2[index_value_3]

NameError: name 'index_value_3' is not defined

In [19]:
index_value_3_UR=np.unravel_index(index_value_3,array_2.shape)

NameError: name 'index_value_3' is not defined

In [20]:
array_2[index_value_3_UR]

NameError: name 'index_value_3_UR' is not defined

In [21]:
array_1[index_value]

array([369, 392, 419, 468, 467])

In [22]:
np.allclose(array_1,array_2,0.1)

ValueError: operands could not be broadcast together with shapes (15,) (3,5) 

In [23]:
np.allclose(array_1,array_2.ravel(),0.1)

True

In [24]:
array_3=np.array([0.12,0.17,0.24])
array_4=np.array([0.13,0.19,0.26])
np.allclose(array_3,array_4,0.1)

False

In [25]:
np.allclose(array_3,array_4,0.2)

True

In [26]:
np.clip(array_1,100,250)

array([224, 158, 250, 100, 100, 250, 250, 250, 242, 100, 250, 250, 205,
       250, 250])

In [27]:
array_1

array([224, 158, 298,  39,  96, 468, 419, 467, 242,  97, 366, 392, 205,
       369, 357])

In [28]:
np.clip(array_2,100,250)

array([[224, 158, 250, 100, 100],
       [250, 250, 250, 242, 100],
       [250, 250, 205, 250, 250]])